
export const PAGE_NAMES = [
    "Dashboard",
    "Daily Plan",
    "Customer Visit Form",
    "User Management",
    "Role Management",
    "Permission Management",
    "Customers",
    "Customers Map",
    "Sellers",
    "Merchandisers",
    "Customer-Seller Relations",
    "Customer-Merch Relations",
    "Seller Product Group Relations",
    "Seller Product Assignments",
    "Seller-Merch Assignments",
    "Visit Types",
    "Send Notification",
    "Track",
    "Sales Route Planning",
    "Merch Route Planning",
    "Visit Requests",
    "Visit Request Merchandiser",
    "Visit Request Report",
    "Visit Request Merch Report",
    "Admin Seller Visit Report",
    "Admin Merch Visit Report",
    "My Visit Requests",
    "Seller Visit Report",
    "Merch Visit Report",
    "Seller Route Report",
    "My Profile",
    "Logo Management",
    "Fixed Asset Brands",
    "Fixed Asset Delivery",
    "Fixed Asset Delivery Report",
    "Sales Dashboard",
    "Products",
    "Product Groups",
    "Competitor Price Analysis",
    "Competitor Price Analysis Report",
    "Competitor Price Analysis AI Report",
    "Product Display",
    "Display Reporting",
    "Product Shelf",
    "Product Shelf Reporting",
    "Product Insert",
    "Product Insert Reporting",
    "My Product Inserts",
    "Problem Types",
    "Report a Problem",
    "Problem Report",
    "Customer Properties",
    "Districts",
    "Sales Route Report",
    "Merch Route Report",
    "Reasons for No Visits",
    "Team Dashboard",
    "Team Reports",
    "Rota Groups",
    "Rota Group Relations",
    "Fixed Asset Form",
    "Fixed Asset Report Customer"
];